### ISSUE TITLE
Curselink?

### ISSUE THREAD

**Issue by jusitnboggs** [KrzysztofSzewczyk/EquivalentExchangeRevamped#1]
I did a quick google and didn't find this on curse is it going to be uploaded there?

**Comment by KrzysztofSzewczyk** [comment]
Of course. I'm working on some finishing touches now.

**Comment by KrzysztofSzewczyk** [comment]
https://www.curseforge.com/minecraft/mc-mods/equivalent-exchange-revived
Well, it's embarrasing, a long time has passed, so here it is.
